-- CreateEnum
CREATE TYPE "JenisKelamin" AS ENUM ('LAKI_LAKI', 'PEREMPUAN');

-- CreateEnum
CREATE TYPE "kategoriProfesi" AS ENUM ('DOKTER_SPESIALIS', 'DOKTER_UMUM', 'DOKTER_GIGI_DAN_MULUT', 'PERAWAT', 'BIDAN', 'FARMASI', 'LABORATORIUM', 'RADIOLOGI', 'GIZI', 'FISIOTERAPI', 'REKAM_MEDIS', 'MANAJEMEN_DAN_ADMIN', 'KEUANGAN', 'IT_DAN_SIMRS', 'IPSRS', 'KEAMANAN', 'LAYANAN_UMUM');

-- CreateEnum
CREATE TYPE "kategoriUnitkerja" AS ENUM ('INSTALASI_GAWAT_DARURAT_IGD', 'RAWAT_INAP', 'POLI_UMUM', 'POLI_GIGI_DAN_MULUT', 'POLI_MATA', 'POLI_PENYAKIT_DALAM', 'POLI_OBYN', 'POLI_ANAK', 'POLI_KULIT_DAN_KELAMIN', 'POLI_THT', 'POLI_KEJIWAAN', 'POLI_REHABILITASI_MEDIK', 'POLI_SYARAF', 'POLI_ORTHOPEDI', 'POLI_BEDAH_UMUM', 'INTENSIVE_CARE_UNIT_ICU_ICCU_HCU_NICU', 'GIZI', 'LABORATORIUM', 'RADIOLOGI', 'FARMASI', 'FISIOTERAPI', 'REKAM_MEDIS', 'MANAJEMEN_DAN_ADMIN', 'KEUANGAN', 'IT_DAN_SIMRS', 'KAMAR_OPERASI_IBS', 'KAMAR_BERSALIN', 'INSTALASI_FARMASI', 'MANEJEMEN_DAN_ADMINISTRASI', 'KEUANGAN_DAN_AKUTANSI', 'DIKLAT_DAN_PENGEMBANGAN_SDM', 'IPSRS', 'KEAMANAN_DAN_KETERTIBAN', 'FRONT_OFFICE_DAN_PENDAFTARAN', 'SANITASI_DAN_LAUNDRY');

-- CreateEnum
CREATE TYPE "kategoriStatuskepegawaian" AS ENUM ('PEGAWAI_TETAP', 'KONTRAK', 'MITRA_DOKTER_TAMU');

-- CreateTable
CREATE TABLE "Staff" (
    "id" SERIAL NOT NULL,
    "idStaff" INTEGER NOT NULL,
    "namaLkG" TEXT NOT NULL,
    "nip" TEXT NOT NULL,
    "jenisKelamin" "JenisKelamin" NOT NULL,
    "alamat" TEXT NOT NULL,
    "noTelp" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "kategoriProfesi" "kategoriProfesi" NOT NULL,
    "kategoriUnitkerja" "kategoriUnitkerja" NOT NULL,
    "jabatanSpesfik" TEXT NOT NULL,
    "statusKepegawaian" "kategoriStatuskepegawaian" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Staff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "staffMedis" (
    "id" SERIAL NOT NULL,
    "idStaff" INTEGER NOT NULL,
    "nip" TEXT NOT NULL,
    "sip" TEXT NOT NULL,

    CONSTRAINT "staffMedis_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Staff_idStaff_key" ON "Staff"("idStaff");

-- CreateIndex
CREATE UNIQUE INDEX "staffMedis_idStaff_key" ON "staffMedis"("idStaff");
