/*
  Warnings:

  - Changed the type of `kategoriUnitkerja` on the `Staff` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- CreateEnum
CREATE TYPE "kategoriUnitKerja" AS ENUM ('INSTALASI_GAWAT_DARURAT_IGD', 'RAWAT_INAP', 'POLI_UMUM', 'POLI_GIGI_DAN_MULUT', 'POLI_MATA', 'POLI_PENYAKIT_DALAM', 'POLI_OBYN', 'POLI_ANAK', 'POLI_KULIT_DAN_KELAMIN', 'POLI_THT', 'POLI_KEJIWAAN', 'POLI_REHABILITASI_MEDIK', 'POLI_SYARAF', 'POLI_ORTHOPEDI', 'POLI_BEDAH_UMUM', 'INTENSIVE_CARE_UNIT_ICU_ICCU_HCU_NICU', 'GIZI', 'LABORATORIUM_PATOLOGI_KLINIK', 'LABORATORIUM_PATOLOGI_ANATOMI', 'BANK_DARAH', 'RADIOLOGI', 'INSTALASI_FARMASI_RAWAT_JALAN', 'INSTALASI_FARMASI_RAWAT_INAP', 'FISIOTERAPI', 'REKAM_MEDIS', 'RUANG_SERVER_DAN_IT_SUPPORT', 'MANAJEMEN_DAN_ADMIN', 'KEUANGAN', 'FRONT_OFFICE', 'BACK_OFFICE', 'HRD_DAN_DIKLAT', 'KAMAR_OPERASI_IBS', 'KAMAR_BERSALIN', 'IPSRS', 'KEAMANAN_DAN_KETERTIBAN', 'SANITASI_DAN_KEBERSIHAN', 'LAUNDRY', 'SUPIR_AMBULANCE', 'CLEANING_SERVICE');

-- AlterTable
ALTER TABLE "Staff" DROP COLUMN "kategoriUnitkerja",
ADD COLUMN     "kategoriUnitkerja" "kategoriUnitKerja" NOT NULL;

-- DropEnum
DROP TYPE "kategoriUnitkerja";
